[package]
name = "iron-guess"
version = "0.0.1"
# Votre courriel!
authors = ["You <you@example.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "0.6.1"
mime = "*"
router = "*"
urlencoded = "*"
